import { CircleLinkModel } from '../wxFind/model/FriendCircleListModel'
import commonHelper from '../wxTools/CommonHelper'
// 头像图片库
export const HeadImageArray: string[] = [
'huige','nituwang','pengpeng','qiangge','shejilushang','shejipai','shejizhijia','siyuansheji','tingting'
  ,'tuyiwang','UIzhongguo','wall_haven','zange','zitibao','design','huabanwang','zitizhijia','junhuoku',
  'youshewang','zhanku','shijueme','uicloud','logostock','zitichuanqi','peiseqi','Colorfavs','cangbiaowang'
  ,'maozhao','mengtu','laoshu','mengtu1','bailing','IMG_4162','IMG_4166','IMG_4164','IMG_4165','IMG_4166'
  ,'IMG_4167','IMG_4168','IMG_4169','IMG_4170','IMG_4171','IMG_4172','IMG_4173','IMG_4174','IMG_4175'
  ,'IMG_4176','IMG_4177','IMG_4178','IMG_4179','IMG_4180','IMG_4181','IMG_4182','IMG_4183','IMG_4184','IMG_4185'
  ,'IMG_4186','IMG_4187','IMG_4188'
]

// 朋友圈背景图片库
export const CoverImageArray: string[] = [
  'IMG_1','IMG_2','IMG_3','IMG_4','IMG_6','IMG_10','IMG_11','IMG_12','IMG_13','IMG_14','IMG_15','IMG_16'
  ,'IMG_18','IMG_19','IMG_23','IMG_24','IMG_25','IMG_26','IMG_27','IMG_28','IMG_29','IMG_33','IMG_34'
  , 'IMG_35','IMG_36','IMG_37','IMG_38','IMG_39','IMG_40','IMG_3927','IMG_3928','IMG_3929','IMG_3930'
  ,'IMG_3931','IMG_3932','IMG_3933','IMG_3934','IMG_3935'
  ,'IMG_3936','IMG_3937','IMG_3938','IMG_3939','IMG_3940','IMG_3941','IMG_3942','IMG_3943','IMG_3944'
  ,'IMG_3945','IMG_3946','IMG_3947','IMG_3948','IMG_3949','IMG_3950','IMG_3951','IMG_3952','IMG_3953','IMG_3954'
  ,'IMG_4162'
]

// 发布朋友圈使用的图片库
export const CircleImageArray: string[] = [
  'IMG_1','IMG_2','IMG_3','IMG_4','IMG_5','IMG_6','IMG_7','IMG_8','IMG_9','IMG_10','IMG_11','IMG_12'
  ,'IMG_13','IMG_14','IMG_15','IMG_16','IMG_17','IMG_18','IMG_19','IMG_20','IMG_21','IMG_22','IMG_23','IMG_24','IMG_25'
  ,'IMG_26','IMG_27','IMG_28','IMG_29','IMG_30','IMG_31','IMG_32','IMG_33','IMG_34','IMG_35','IMG_36','IMG_37','IMG_38'
  ,'IMG_39','IMG_40','IMG_3927','IMG_3928','IMG_3929','IMG_3930','IMG_3931','IMG_3932','IMG_3933','IMG_3934','IMG_3935'
  ,'IMG_3936','IMG_3937','IMG_3938','IMG_3939','IMG_3940','IMG_3941','IMG_3942','IMG_3943','IMG_3944','IMG_3945','IMG_3946'
  ,'IMG_3947','IMG_3948','IMG_3949','IMG_3950','IMG_3951','IMG_3952','IMG_3953','IMG_3954'
]

// 发布朋友圈使用的Link Content
export const LinkModelList: CircleLinkModel[] = [
  {
    link_image: 'IMG_3988',
    link_text: '美国宇航员滞留太空150天 瘦到脱相下巴尖得像锥子',
    link_url: 'https://c.m.163.com/news/a/JGKV2HRP0550A0OW.html'
  },
  {
    link_image: 'IMG_3989',
    link_text: '雷竞技资讯：买下Bin和Chovy冲击S15冠军！EDG银河战舰阵容太豪华',
    link_url: 'https://c.m.163.com/news/a/JGKR74GH0526WRT0.html?spss=newsapp&spsnuid=&spsdevid=1FB9E311-8567-4716-9ADC-20692016E1C6&spsvid=&spsshare=wx&spsts=1731230392284&spstoken=rudwHLk%2FjCy9HLDaUjtNLqytOcuGvfpJtJ1%2BzcqA%2BHhp3FYT%2Fh1vl0s5WnHnEyWx'
  }
]

// 发布朋友圈使用的Link Content
export const LocationNames: string[] = [
  '西城区 · 天安门广场','西城区 · 故宫博物院', '北京 · 圆明园', '北京 · 颐和园', '北京 · 八达岭长城', '海淀区 · 清华大学', '海淀区 · 北京大学'
  ,'郑州市 · 二七广场', '高新区 · 西流湖公园', '上海 · 外滩', '南京 · 中山陵', '杭州 · 西湖', '西安 · 大雁塔', '四川 · 九寨沟', '安徽 · 黄山'
]